# Generated by Django 3.1.7 on 2021-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('continent_code', models.CharField(max_length=200)),
                ('continent_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=200)),
                ('region_code', models.CharField(max_length=200)),
                ('region_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
